### ISSUE TITLE
Add undo/redo

### ISSUE THREAD

**Issue by haydn** [haydn/sketchbook#29]
Here's a  library some cool guy has made that would work pretty well:

https://github.com/haydn/use-state-snapshots

We'd probably want to use it without automatic snapshots enabled and with a limited number of snapshots saved:

```js
const [state, setState, pointer, setPointer] = useState({...}, false, 100);
```

Almost all of the the places where we call `setState` should be updated to have a second argument of `true` to force a snapshot (the exceptions will be when the view is updating, such as mouse position):

```js
setState(current => ({ ...current }), true);
```

We can just chuck some buttons above the layers or something like that for now that let the user undo/redo:

```jsx
<button
  onClick={() => {
    setPointer(pointer - 1);
  }}
>
  Undo
</button>
<button
  onClick={() => {
    setPointer(pointer + 1);
  }}
>
  Redo
</button>
```

**Comment by Mxchaeltrxn** [comment]
Could you assign me to this issue?
